package com.raaed.employee.management.service;

import com.raaed.employee.management.model.Employee;
import com.raaed.employee.management.repository.EmployeeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.List;

//service class handling storage logic
@Service
public class EmployeeService {

    private final EmployeeRepository employeeRepository;

    @Autowired
    // gets the bean employee repository, which is auto generated by spring because of IOC
    public EmployeeService(EmployeeRepository employeeRepository) {
        this.employeeRepository = employeeRepository;
    }

    public List<Employee> getAllEmployees() {
        return employeeRepository.findAll();
    }

    @Autowired
    private PasswordEncoder passwordEncoder;

    public Employee saveEmployee(Employee employee) {
        // Hash the password before saving
        employee.setPassword(passwordEncoder.encode(employee.getPassword()));
        return employeeRepository.save(employee);
    }


    // Native
    public List<Employee> getEmployeesByDepartment(String department) {
        return employeeRepository.findByDepartmentNative(department);
    }

}
